### ISSUE TITLE
Why not suitable for Validator?

### ISSUE THREAD

**Issue by dcale** [RyanHendricks/docker-cosmos#5]
You wrote in the notes, this setup shouldn't be used for validators. Since I think the isolation given from the containerization I thought, it might be useful to have a validator running in a container. So I was wondering why you wouldn't suggest to use it for a validator (assuming everything is built locally and the parent images have been security reviewed)?

**Comment by RyanHendricks** [comment]
Hi,

Thanks for your interest in and the project and I'm sorry for the late response. Two reasons why I made that suggestion.

The first is simply to limit my own liability if someone using this setup were to lose funds or have any sort of issues (although not likely). This node would be connected directly to the internet (unless configured otherwise) and might not be as secure from various attack vectors as would a node behind trusted sentry nodes.

The second reason is the configuration is aimed more towards a node used used mainly for api calls (txindex all, cache size, etc.). However, realistically, one could certainly use the setup for a validator so long as they understand a little bit about what's going on under the hood; especially if built locally and parent images security reviewed as you mentioned.

Much of this could also be handled on the infrastructure level and/or deployment via Kubernetes ([example configs](https://github.com/RyanHendricks/ivy-mike/tree/master/kubernetes/cosmos)).

Hope this helps!

**Comment by dcale** [comment]
perfect, thank you for the reply. This makes a lot of sense. Can be closed.
